import { Property } from '@/components/property-card';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Magnifique Appartement 3 Pièces - Douala Akwa',
    price: 450000,
    location: 'Douala, Akwa',
    city: 'Douala',
    bedrooms: 3,
    bathrooms: 2,
    squareMeter: 85,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
    type: 'Appartement',
    transaction: 'À louer',
    isNew: true,
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Villa Moderne avec Piscine - Douala Bonanjo',
    price: 150000000,
    location: 'Douala, Bonanjo',
    city: 'Douala',
    bedrooms: 5,
    bathrooms: 4,
    squareMeter: 320,
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop',
    type: 'Villa',
    transaction: 'À vendre',
    isUrgent: true,
  },
  {
    id: '3',
    title: 'Studio Cozy - Yaoundé Bastos',
    price: 200000,
    location: 'Yaoundé, Bastos',
    city: 'Yaoundé',
    bedrooms: 1,
    bathrooms: 1,
    squareMeter: 35,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
    type: 'Studio',
    transaction: 'À louer',
    isNew: true,
  },
  {
    id: '4',
    title: 'Maison Spacieuse - Yaoundé Etoudi',
    price: 80000000,
    location: 'Yaoundé, Etoudi',
    city: 'Yaoundé',
    bedrooms: 4,
    bathrooms: 3,
    squareMeter: 250,
    image: 'https://images.unsplash.com/photo-1570129477492-45a003537e1f?w=800&h=600&fit=crop',
    type: 'Maison',
    transaction: 'À vendre',
    isFeatured: true,
  },
  {
    id: '5',
    title: 'Appartement Moderne - Douala Bali',
    price: 350000,
    location: 'Douala, Bali',
    city: 'Douala',
    bedrooms: 2,
    bathrooms: 2,
    squareMeter: 65,
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=600&fit=crop',
    type: 'Appartement',
    transaction: 'À louer',
  },
  {
    id: '6',
    title: 'Terrain Constructible - Douala Bonapriso',
    price: 25000000,
    location: 'Douala, Bonapriso',
    city: 'Douala',
    bedrooms: 0,
    bathrooms: 0,
    squareMeter: 500,
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=600&fit=crop',
    type: 'Terrain',
    transaction: 'À vendre',
  },
  {
    id: '7',
    title: 'Commerce Aménagé - Yaoundé Centre',
    price: 600000,
    location: 'Yaoundé, Centre',
    city: 'Yaoundé',
    bedrooms: 0,
    bathrooms: 1,
    squareMeter: 120,
    image: 'https://images.unsplash.com/photo-1554995207-c18e338fdda1?w=800&h=600&fit=crop',
    type: 'Commerce',
    transaction: 'À louer',
    isNew: true,
  },
  {
    id: '8',
    title: 'Luxueux Penthouse - Douala Akwa',
    price: 250000000,
    location: 'Douala, Akwa',
    city: 'Douala',
    bedrooms: 6,
    bathrooms: 5,
    squareMeter: 450,
    image: 'https://images.unsplash.com/photo-1613584217057-292f3cfee75d?w=800&h=600&fit=crop',
    type: 'Appartement',
    transaction: 'À vendre',
    isFeatured: true,
  },
  {
    id: '9',
    title: 'Maison Familiale - Buea',
    price: 55000000,
    location: 'Buea, Residential',
    city: 'Buea',
    bedrooms: 3,
    bathrooms: 2,
    squareMeter: 180,
    image: 'https://images.unsplash.com/photo-1480074568153-71b99200a0f0?w=800&h=600&fit=crop',
    type: 'Maison',
    transaction: 'À vendre',
  },
  {
    id: '10',
    title: 'Appartement T2 - Bamenda Downtown',
    price: 280000,
    location: 'Bamenda, Downtown',
    city: 'Bamenda',
    bedrooms: 2,
    bathrooms: 1,
    squareMeter: 55,
    image: 'https://images.unsplash.com/photo-1501183007986-e0e079abd373?w=800&h=600&fit=crop',
    type: 'Appartement',
    transaction: 'À louer',
    isUrgent: true,
  },
  {
    id: '11',
    title: 'Studio Climatisé - Garoua',
    price: 150000,
    location: 'Garoua, Centre',
    city: 'Garoua',
    bedrooms: 1,
    bathrooms: 1,
    squareMeter: 40,
    image: 'https://images.unsplash.com/photo-1486899430790-61dbf6f6d98b?w=800&h=600&fit=crop',
    type: 'Studio',
    transaction: 'À louer',
  },
  {
    id: '12',
    title: 'Villa avec Jardin - Limbe',
    price: 95000000,
    location: 'Limbe, Residential',
    city: 'Limbe',
    bedrooms: 4,
    bathrooms: 3,
    squareMeter: 280,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop',
    type: 'Villa',
    transaction: 'À vendre',
  },
];

export const popularCities = [
  { name: 'Douala', count: 245 },
  { name: 'Yaoundé', count: 189 },
  { name: 'Buea', count: 42 },
  { name: 'Bamenda', count: 38 },
  { name: 'Garoua', count: 25 },
  { name: 'Limbe', count: 18 },
];

export const features = [
  {
    title: 'Annonces Vérifiées',
    description: 'Tous nos annonces sont vérifiées pour garantir votre sécurité',
    icon: '✓',
  },
  {
    title: 'Paiement Sécurisé',
    description: 'Transactions sécurisées et protégées',
    icon: '🔒',
  },
  {
    title: 'Contact Direct',
    description: 'Connectez-vous facilement avec propriétaires',
    icon: '📱',
  },
  {
    title: 'Large Sélection',
    description: 'Des milliers de propriétés au Cameroun',
    icon: '🏠',
  },
];
